# Generated by Django 4.2.6 on 2023-10-29 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('dob', models.DateField()),
                ('city', models.CharField(choices=[('', '-----'), ('Atlanta', 'Atlanta'), ('Columbus', 'Columbus'), ('Augusta', 'Augusta'), ('Macon', 'Macon'), ('Savannah', 'Savannah')], max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('', '-----'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('education', models.CharField(choices=[('', '-----'), ('shs', 'Some High School'), ('hs', 'High School'), ('col', 'College'), ('grad', 'Graduate'), ('others', 'Others')], max_length=10)),
                ('move_in_date', models.DateField()),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoommatePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours', models.PositiveIntegerField()),
                ('drinks', models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=10)),
                ('drugs', models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=10)),
                ('smoke', models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=10)),
                ('loud_music', models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=10)),
                ('rooms', models.PositiveIntegerField()),
                ('budget', models.PositiveIntegerField()),
                ('meals', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pets', models.ManyToManyField(blank=True, to='webapp.petchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, to='webapp.interestchoice')),
                ('pets_allowed', models.ManyToManyField(blank=True, to='webapp.petchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
