# Generated by Django 4.2.6 on 2023-10-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_userinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinterest',
            old_name='confirmed',
            new_name='accept',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
